spring:
  datasource:
    url: jdbc:postgresql://ep-withered-butterfly-a850paz4-pooler.eastus2.azure.neon.tech/neondb?sslmode=require
    driver-class-name: org.postgresql.Driver
    username: neondb_owner
    password: SENHA_AQUI # Substitua pela senha correta
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect